import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: { backgroundColor: "rgba(2,6,23,0.40)" },

  modal: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#0B1220",
    overflow: "hidden",
  },
  handle: {
    width: 60,
    height: 5,
    backgroundColor: "rgba(148,163,184,0.35)",
    borderRadius: 999,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 4,
  },

  headerWrap: { backgroundColor: "#0B1220" },
  headerGlow: {
    position: "absolute",
    top: -120,
    left: -40,
    right: -40,
    height: 220,
    borderRadius: 220,
    backgroundColor: "rgba(56,189,248,0.18)",
    transform: [{ scaleX: 1.2 }],
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  heroIcon: {
    width: 48,
    height: 48,
    borderRadius: 18,
    backgroundColor: "rgba(56,189,248,0.18)",
    borderWidth: 1,
    borderColor: "rgba(56,189,248,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroEmoji: { fontSize: 22 },
  headerTitle: { color: "#E2E8F0", fontWeight: "900", fontSize: 18 },
  headerSub: { color: "rgba(226,232,240,0.75)", marginTop: 2, fontSize: 12 },
  closeBtn: {
    marginLeft: "auto",
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: "rgba(148,163,184,0.12)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  closeText: { color: "#E2E8F0", fontSize: 22, lineHeight: 22, fontWeight: "900" },

  body: {
    backgroundColor: "#F6F7FB",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 18,
  },

  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(226,232,240,0.95)",
    marginBottom: 12,
    shadowColor: "#0B1220",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 14 },
  },
  cardTitle: { fontWeight: "950" as any, color: "#0F172A", fontSize: 15 },
  cardSub: { marginTop: 6, color: "#64748B", fontSize: 12.5, fontWeight: "700" },

  smallLabel: { fontWeight: "900", color: "#0F172A", marginBottom: 8, fontSize: 12 },

  inputShell: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  inlineEmoji: { fontSize: 18 },
  textInput: { flex: 1, color: "#0F172A", fontSize: 15.5, paddingVertical: 0, fontWeight: "700" },

  helper: { marginTop: 8, color: "#64748B", fontSize: 12, fontWeight: "800" },

  segmented: {
    flexDirection: "row",
    gap: 10,
    padding: 6,
    borderRadius: 18,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  segmentBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  segmentBtnActive: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(15,23,42,0.10)",
    shadowColor: "#0B1220",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  segmentLabel: { color: "#0F172A", fontWeight: "950" as any, fontSize: 14 },
  segmentLabelActive: { color: "#0A84FF" },
  segmentHint: { marginTop: 2, color: "#64748B", fontWeight: "800", fontSize: 11 },
  segmentHintActive: { color: "rgba(10,132,255,0.85)" },

  pricePrefix: { color: "#0F172A", fontWeight: "950" as any, fontSize: 16 },
  priceInput: { flex: 1, color: "#0F172A", fontSize: 15.5, paddingVertical: 0, fontWeight: "800" },
  goodPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(34,197,94,0.12)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.25)",
  },
  goodPillText: { color: "#166534", fontWeight: "900", fontSize: 12 },

  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 2,
  },
  toggleTitle: { color: "#0F172A", fontWeight: "950" as any, fontSize: 14.5 },
  toggleSub: { marginTop: 4, color: "#64748B", fontWeight: "800", fontSize: 12.5 },

  chevPill: {
    width: 34,
    height: 34,
    borderRadius: 14,
    backgroundColor: "rgba(148,163,184,0.14)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
    alignItems: "center",
    justifyContent: "center",
  },
  chevPillOpen: {
    backgroundColor: "rgba(10,132,255,0.10)",
    borderColor: "rgba(10,132,255,0.22)",
  },
  chevText: { color: "#0F172A", fontWeight: "950" as any, fontSize: 18, lineHeight: 18 },
  chevTextOpen: { color: "#0A84FF" },

  descShell: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  descInput: { minHeight: 110, color: "#0F172A", fontSize: 15, fontWeight: "700" },

  locationIcon: { fontSize: 16 },
  locationInput: { flex: 1, color: "#0F172A", fontSize: 15.5, paddingVertical: 0, fontWeight: "700" },

  iconBtn: {
    width: 30,
    height: 30,
    borderRadius: 12,
    backgroundColor: "rgba(100,116,139,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  iconBtnText: { color: "#334155", fontSize: 18, fontWeight: "900", lineHeight: 18 },

  dropdown: {
    marginTop: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  dropdownLoading: { flexDirection: "row", alignItems: "center", gap: 10, padding: 12 },
  dropdownLoadingText: { color: "#64748B", fontWeight: "800" },

  dropdownRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E2E8F0",
  },
  dropdownMain: { color: "#0F172A", fontWeight: "950" as any, fontSize: 14 },
  dropdownSecondary: { color: "#64748B", marginTop: 3, fontSize: 12, fontWeight: "700" },
  dropdownArrow: { color: "#94A3B8", fontSize: 18, fontWeight: "900", marginLeft: 10 },

  pill: {
    marginTop: 10,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    maxWidth: "100%",
  },
  pillSuccess: { backgroundColor: "rgba(34,197,94,0.12)", borderColor: "rgba(34,197,94,0.25)" },
  pillInfo: { backgroundColor: "rgba(14,165,233,0.10)", borderColor: "rgba(14,165,233,0.22)" },
  pillText: { fontWeight: "900", fontSize: 12 },
  pillTextSuccess: { color: "#166534" },
  pillTextInfo: { color: "#075985" },

  inlineLoading: { marginTop: 12, flexDirection: "row", alignItems: "center", gap: 10 },
  inlineLoadingText: { color: "#64748B", fontWeight: "900" },

  whenGrid: { flexDirection: "row", gap: 10, marginTop: 4 },
  whenTile: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    padding: 14,
    shadowColor: "#0B1220",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 10 },
  },
  whenTileTop: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 10 },
  whenBadge: { width: 30, height: 30, borderRadius: 10, alignItems: "center", justifyContent: "center", borderWidth: 1 },
  whenBadgeBlue: { backgroundColor: "rgba(10,132,255,0.12)", borderColor: "rgba(10,132,255,0.22)" },
  whenBadgePurple: { backgroundColor: "rgba(139,92,246,0.12)", borderColor: "rgba(139,92,246,0.22)" },
  whenBadgeText: { fontSize: 14 },
  whenTileLabel: { color: "#64748B", fontWeight: "900", fontSize: 12 },
  whenTileValue: { color: "#0F172A", fontWeight: "950" as any, fontSize: 16, letterSpacing: -0.2 },
  whenTileValueMuted: { color: "#94A3B8" },
  whenTileHint: { marginTop: 6, color: "#64748B", fontWeight: "800", fontSize: 12 },

  clearPill: {
    marginTop: 12,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(148,163,184,0.14)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.22)",
  },
  clearPillText: { color: "#0F172A", fontWeight: "950" as any, fontSize: 12 },

  pickerOverlay: { flex: 1, backgroundColor: "rgba(2,6,23,0.45)", padding: 16, justifyContent: "flex-end" },
  pickerCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
    paddingBottom: 10,
  },
  pickerTitle: {
    padding: 14,
    fontWeight: "950" as any,
    color: "#0F172A",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  pickerDone: {
    marginTop: 8,
    marginHorizontal: 12,
    borderRadius: 14,
    paddingVertical: 12,
    backgroundColor: "#0A84FF",
    alignItems: "center",
  },
  pickerDoneText: { color: "#fff", fontWeight: "950" as any },

  mapWrap: {
    marginTop: 12,
    height: 210,
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#0B1220",
  },
  map: { flex: 1, backgroundColor: "#0B1220" },

  mapOverlay: {
    position: "absolute",
    top: 10,
    left: 10,
    right: 10,
    alignItems: "flex-start",
  },
  mapOverlayPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(15,23,42,0.75)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.18)",
  },
  mapOverlayText: { color: "#E2E8F0", fontWeight: "900", fontSize: 12 },

  mapFallback: { flex: 1, padding: 16, justifyContent: "center" },
  mapFallbackTitle: { color: "#E2E8F0", fontWeight: "900", fontSize: 14 },
  mapFallbackBody: { color: "rgba(226,232,240,0.78)", marginTop: 8, lineHeight: 18 },

  err: { marginTop: 12, color: "#DC2626", fontWeight: "900" },

  actions: { flexDirection: "row", gap: 12, marginTop: 2 },
  secondaryBtn: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  secondaryText: { color: "#0F172A", fontWeight: "950" as any },

  primaryBtn: {
    flex: 1.6,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0A84FF",
    shadowColor: "#0A84FF",
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 14 },
  },
  primaryText: { color: "#FFFFFF", fontWeight: "950" as any },
});
